pipelines:
  tags:
    staging-*:
      - step:
          name: Build and release
          script:
            - chmod 755 ./script/dependency_injection.sh
            - ./script/dependency_injection.sh staging
            - docker build . --target prod --tag nextjs-on-ecs-server
            - pipe: atlassian/aws-ecr-push-image:1.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ECR_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_ECR_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: nextjs-on-ecs-server
                TAGS: '${BITBUCKET_TAG}'

          caches:
            - docker

    production-*:
      - step:
          name: Build and release
          script:
            - chmod 755 ./script/dependency_injection.sh
            - ./script/dependency_injection.sh production
            - docker build . --target prod --tag nextjs-on-ecs-server
            - pipe: atlassian/aws-ecr-push-image:1.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ECR_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_ECR_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: nextjs-on-ecs-server
                TAGS: '${BITBUCKET_TAG}'

          caches:
            - docker

  default:
    - step:
        name: Test
        services:
          - docker
        script:
          - chmod 755 ./script/dependency_injection.sh
          - ./script/dependency_injection.sh
          - docker build . --target build --tag nextjs-test-server
          - docker run nextjs-test-server yarn test
        caches:
          - docker
definitions:
  services:
    docker:
      memory: 3072