pipelines:
  default:
    - step:
        name: Test
        services:
          - docker
        script:
          - docker build
          - yarn
          - yarn test
        caches:
          - docker
          - node