pipelines:
  default:
    - step:
        name: Test
        services:
          - docker
        script:
          - docker build .
          - docker ps
#          - bash yarn test
        caches:
          - docker
          - node
definitions:
  services:
    docker:
      memory: 2048