pipelines:
  default:
    - step:
        name: Test
        services:
          - docker
        script:
          - docker build .
          - docker exec -it docker yarn test
        caches:
          - docker
          - node