pipelines:
  default:
    - step:
        name: Test
        services:
          - docker
        script:
          - docker build . -t next
          - docker run --name next -it next /bin/bash
          - docker exec next yarn test
        caches:
          - docker
          - node
definitions:
  services:
    docker:
      memory: 2048