version: '3.7'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app:delegated
#    env_file: .env
    ports:
      - "3000:3000"
    tty: true
    init: true