version: '3.7'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: "node"
    volumes:
      - ./src:/app/src:delegated
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./.env:/app/.env
    ports:
      - "3000:3000"
    tty: true

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "swagger-ui"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    ports:
      - "9001:8080"

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: "swagger-editor"
    ports:
      - "9002:8080"

  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "9003:8000"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    command: /openapi.yaml --watch
