version: '3.7'

services:
  node:
    image: nakajimai/next_app:latest
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: dev
    container_name: "node"
    volumes:
      - .:/app:delegated
#    env_file: .env
    ports:
      - "3000:3000"
    tty: true